### ISSUE TITLE
Keybind doesn't work

### ISSUE THREAD

**Issue by DanDragonWolf** [Flazhik/CybergrindMusicExplorer#11]
I just installed the mod, and the Keybind to open the mod's oprions menu doesn't work. I am also unable to open the options menu for the game itself unless I'm in the main menu.

**Comment by DanDragonWolf** [comment]
Oh wait, that's in the new layer update... I'm dumb lol

**Comment by Flazhik** [comment]
@DanDragonWolf Hey there! Yeah, Violence layer update got me good. I've just recently released a fixed 1.6.1 version, so it should be working now
