### ISSUE TITLE
ffmpeg isnt downloading

### ISSUE THREAD

**Issue by jeamian** [Flazhik/CybergrindMusicExplorer#16]
download just goes up to 3% and then it stops downloading, i have no idea if this is a bug or if it has to do with my pc, so if there was a way to download manually it would help a lot

**Comment by Flazhik** [comment]
@jeamian You can install it manually
1.Download ffmpeg archive manually from here https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
2. Open the folder `ffmpeg-master-latest-win64-gpl\bin` inside it
3. Extract `ffmpeg.exe` and `ffprobe.exe` into the same folder when `CybergrindMusicExplorer.dll` is located. If you've installed the mod manually, it's `ULTRAKILL\BepInEx\plugins\CybergrindMusicExplorer`. If you're using r2modman the path is a little bit trickier: `C:\Users\{YourUsername}\AppData\Roaming\r2modmanPlus-local\ULTRAKILL\profiles\{ProfileName}\BepInEx\plugins\Flazhik-CybergrindMusicExplorer\CybergrindMusicExplorer`

**Comment by jeamian** [comment]
> @jeamian You can install it manually 1.Download ffmpeg archive manually from here https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip 2. Open the folder `ffmpeg-master-latest-win64-gpl\bin` inside it 3. Extract `ffmpeg.exe` and `ffprobe.exe` into the same folder where `CybergrindMusicExplorer.dll` is located. If you've installed the mod manually, it's `ULTRAKILL\BepInEx\plugins\CybergrindMusicExplorer`. If you're using r2modman the path is a little bit trickier: `C:\Users\{YourUsername}\AppData\Roaming\r2modmanPlus-local\ULTRAKILL\profiles\{ProfileName}\BepInEx\plugins\Flazhik-CybergrindMusicExplorer\CybergrindMusicExplorer`

thanks a lot
