### ISSUE TITLE
indefinitely (almost)

### ISSUE THREAD

**Issue by surytrap** [Flazhik/CybergrindMusicExplorer#3]
when "show current track panel indefinitely" is turned on and a song with intro and loop plays, track panel disappears after intro ends and loop starts

**Comment by Flazhik** [comment]
Thank you for reporting, I'll fix it in the next update.

**Comment by Flazhik** [comment]
Fixed in https://github.com/Flazhik/CybergrindMusicExplorer/commit/656d6be3cc86470af81e600e9f52a55e8916cf59
