### ISSUE TITLE
Load Subtitles via .txt file

### ISSUE THREAD

**Issue by UntotenTheo** [Flazhik/CybergrindMusicExplorer#4]
a bit of a weird request, but what if we could load subtitles for songs from a text file?

the formatting would probably be something simple like;

[00:00] "Lines go here"
[00:05] "Lines go here, again!"

the .txt file itself would probably just be named smth like songName_lyrics.txt
and for songs with a loop and intro, it'd be songName_loop/intro_lyrics
this would be a silly addition   but  yeah

**Comment by Flazhik** [comment]
You won't believe me, but this idea had actually crossed my mind at some point.
Why not, I can do it 😄 But most likely I'll use .srt subtitles format instead.

**Comment by UntotenTheo** [comment]
omg,,,

**Comment by Flazhik** [comment]
@UntotenTheo Done, new release 1.3.1 is ready. Should be available on Thunderstore soon too.

**Comment by SkylaLZ** [comment]
Will this ever be re-added to the rewrite? Kind of a bummer it got removed.
