### ISSUE TITLE
Segmented Tracks in playlist only playing one segment

### ISSUE THREAD

**Issue by LucyArts64** [Flazhik/CybergrindMusicExplorer#5]
For most of the tracks I add, I like to make them segmented (intro/loop). But when I put multiple of them in a playlist, the next track only plays the "_loop" file without the "_intro" part even though it's a different song which kinda throws it off.
Not sure if this is intentional or not but I wanted to bring it up in case it wasn't. Mod's amazing btw.

**Comment by Flazhik** [comment]
@LucyArts64 Thanks a lot, hope you're enjoying it!
This is the way vanilla Ultrakill manages multiple multisegmented tracks: the only time an intro part is played is when it's the first track in the queue, so I decided to leave this logic as is. 
Nevertheless, appreciate for the report
